name: A workflow for my Hello World file
on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Name
        options:
          - Hoge
          - Fuga
          - Poi
      message:
        required: true
        default: "Write some message here"
      dryrun:
        type: boolean
        description: Is dryrun?
        default: true

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
  duplicate_build:
      name: Same Action
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - uses: ./action-a
          with:
            MY_NAME: ${{ github.event.inputs.name }}
